name: Docs

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Build docs
        run: (cd docs && npm ci && npm run docs:build)
      - name: Add .nojekyll
        run: (cd public && touch .nojekyll)
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./public
